version: "3"

services:
  geoconvertor:
    image: geoconvertor:latest
    container_name: geoconvertor
    volumes:
      - ./template.geojson:/app/template.geojson
    command: ["dotnet", "GeoJsonConvertor.dll", "template.geojson", "2020-01-01", "2024-06-01"]

networks:
  default:


  
